config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies do
  	resources :reviews
  end
  root 'movies#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :movies
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
	has_many :reviews

	belongs_to :bulletin
  	mount_uploader :picture, PictureUploader

	
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :movies
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :movies
	has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :find_book, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def index
		if 
			params[:category].blank?
			@movies = Movie.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@movies = Movie.where(:category_id => @category_id).order("created_at DESC")
		end
	end

	def show
		if 
			@movie.reviews.blank?
			@average_review = 0
		else
			@average_review = @movie.reviews.average(:rating).round(2)
		end
	end

	def new
		@movie = current_user.movies.build
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def create
		@movie = current_user.movies.build(movie_params)
		@movie.category_id = params[:category_id]

		if 
			@movie.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def update

		@movie.category_id = params[:category_id]
		
		if 
			@movie.update(movie_params)
			redirect_to movie_path(@movie)
		else
			render 'edit'
		end
	end

	def destroy
		@movie.destroy
		redirect_to root_path
	end

	private

	def movie_params
		params.require(:movie).permit(:title, :description, :director, :category_id, :picture, :picture_cache)
	end

	def find_book
		@movie = Movie.find(params[:id])
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_movie
	before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.movie_id = @movie.id
		@review.user_id = current_user.id

		if 
			@review.save
			redirect_to movie_path(@movie)
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update

		if 
			@review.update(review_params)
			redirect_to movie_path(@movie)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to movie_path(@movie)
	end

	private

	def review_params
		params.require(:review).permit(:rating, :comment)
	end

	def find_movie
		@movie = Movie.find(params[:movie_id])
	end

	def find_review
		@review = Review.find(params[:id])
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
				<%= link_to "Movie Review", root_path, class: "navbar-brand" %>
			</div>

			<ul class="nav navbar-nav">
				<li><%= link_to "회원가입", new_user_registration_path %></li>
				<% if user_signed_in? %>
					<li><%= link_to "로그아웃", destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><%= link_to "로그인", new_user_session_path %></li>
				<% end %>
			</ul>

			<ul class="nav navbar-nav navbar-right">

				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories<span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<% Category.all.each do |category| %>
							<li class="<%= 'active' if params[:category] == category.name %>">
								<%= link_to category.name, movies_path(category: category.name), class: "link" %>
							</li>
						<% end %>
					</ul>
				</li>

				<% if user_signed_in? %>
				<li><%= link_to "Add Movie", new_movie_path %></li>
				<% end %>
			</ul>

		</div>
	</nav>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/movies/_form.html.erb
<%= simple_form_for @movie, :html => {:multipart =>true} do |f| %>
	<%= select_tag(:category_id, options_for_select(@categories), :prompt => "카테고리를 선택하세요." ) %>
	<%= f.input :picture, as: :file %>
    <%= f.hidden_field :picture_cache %>
	<%= f.input :title, label: "Movie Title" %>
	<%= f.input :description %>
	<%= f.input :director %>
	<%= f.button :submit, :class => 'btn-custom2' %>
<% end %>

app/views/movies/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="edit-movie-form">

		<h1>Edit Movie</h1>
		<%= simple_form_for @movie, :html => {:multipart =>true} do |f| %>
			<%= f.select :category_id, @categories %>
			<%= f.file_field :picture %>
			<%= f.input :title, label: "Movie Title" %>
			<%= f.input :description %>
			<%= f.input :director %>
			<%= f.button :submit %>
		<% end %>
	</div>
</div>

app/views/movies/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @movies.count == 0 %>
	<h1>카테고리에 새로 추가된 영화가 없습니다.</h1>
<% else %>
	<div class="row">
		<% @movies.each do |movie| %>
			<div class="col-md-3">
				<a href="/movies/<%= movie.id %>">
					<%= image_tag movie.picture.url(:thumb), class: "movie" %>
				</a>
			</div>
		<% end %>
	</div>
<% end %>

app/views/movies/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="new-movie-form">

		<h1>영화 등록</h1>

		<%= render 'form' %>
	</div>
</div>

app/views/movies/show.html.erb
<div class="row">
	<div class="col-md-4">
		<%= image_tag @movie.picture.url(:thumb), class: "movie-show" %>
	</div>

	<div class="col-md-8">
		<div class="movie-info">
			<h2 class="movie-title"><%= @movie.title %></h2>
			<h3 class="movie-director"><span>감독: </span> <%= @movie.director %></h3>
			<h4 class="avg-rating">평균 평점</h4>
			<div class="average-review-rating" data-score=<%= @average_review %>></div>
			<span class="number-of-reviews"><%= @movie.reviews.count %>개의 review</span>
			<p class="movie-desc"><%= @movie.description %></p>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="reviews">
		<!-- ratings will go-->
			<h1>reviews</h1>
			<%= render @movie.reviews %>


			<div>
				<%= link_to "리뷰등록", new_movie_review_path(@movie), class: "btn btn-custom" %>
			</div>
		</div>
	</div>
</div>

<div class="links btn-group">
	<%= link_to "뒤로", root_path, class: "btn btn-custom" %> 

	<% if user_signed_in? %>
		<% if @movie.user_id == current_user.id %>
			<%= link_to "수정", edit_movie_path(@movie), class: "btn btn-custom" %>
			<%= link_to "삭제", movie_path(@movie), method: :delete, data: { confirm: "정말 삭제하시겠습니까?" }, class: "btn btn-custom" %>
		<% end %>
	<% end %>
</div>

<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function(){
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>

<script>
	$('.average-review-rating').raty({
		readOnly: true,
		score: function(){
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>

app/views/reviews/_form.html.erb
<%= simple_form_for([@movie, @movie.reviews.build]) do |f| %>
	<div id="rating-form">
		<label>별점</label>
	</div>
	<%= f.input :comment %>
	<%= f.button :submit, :class => "btn btn-custom2" %>
<% end %>

<script>
	$('#rating-form').raty({
			path: '/assets/',
			scoreName: 'review[rating]' 
		});
</script>

app/views/reviews/_review.html.erb
<div class="review">
	<div class="review-rating" data-score="<%= review.rating %>"></div>
	<p class="review-comment"><%= review.comment %></p>

	<% if user_signed_in? %>
		<% if review.user_id == current_user.id %>

			<div class="links btn-group">
				<%= link_to "edit", edit_movie_review_path(@movie, review), class: "btn btn-custom" %> 
				<%= link_to "delete", movie_review_path(@movie, review), method: :delete, data: { confirm: "정말 삭제하시겠습니까?" }, class: "btn btn-custom" %>
			</div>
		<% end %>
	<% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="edit-review-form">
		<h1>리뷰 수정</h1>

		<%= simple_form_for([@movie, @review]) do |f| %>
			<div id="rating-form">
				<label>별점</label>
			</div>
			<%= f.input :comment %>
			<%= f.button :submit, :class => "btn btn-custom2" %>
		<% end %>
	</div>
</div>

<script>
	$('#rating-form').raty({
			path: '/assets/',
			scoreName: 'review[rating]' 
		});
</script>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="new-review-form">
		<h1>새로운 리뷰</h1>

		 <%= render 'form' %>
 	</div>
</div>